name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.4  # Check for the latest version
  image_picker: ^1.0.7 
  flutter_dotenv: ^5.0.2
  flutter_drawing_board: ^0.9.5

dev_dependencies:  
  font_awesome_flutter: ^10.7.0
  email_validator: ^2.1.17
  sign_in_with_apple: ^5.0.0
  google_sign_in: ^6.2.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - lib/images/play.png
